apiVersion: v1
kind: Pod
metadata:
  name: deployment-manager-test
  namespace: production
spec:
  serviceAccountName: deployment-manager
  containers:
    - name: kubectl
      image: bitnami/kubectl:latest
      command: ["sleep", "3600"]
